[base]
env_name = drone

[vec]
total_agents = 2048
num_buffers = 8
num_threads = 0

[env]
num_drones = 64

# multi-task step fractions
hover_frac = 0.9380512768761159
race_frac = 0.746068257208172
sphere_frac = 0.0
cube_frac = 0.0
flag_frac = 0.0

# domain randomisation
dr = 0.05

# shared rewards
alpha_vel = 0.0
alpha_omega = 0.0
alpha_action = 0.0

# hover
sphere_radius = 4.0
hover_target_dist = 5
hover_horizon = 1024
alpha_hover = 0.11285179026130304
hover_alpha_dist = 0.06414028490661208

# race
max_rings = 10
race_horizon = 2048
ring_reward = 16.091089769730946
race_alpha_dist = 0.46067501660035864

[policy]
expansion_factor = 1
hidden_size = 128
num_layers = 3

[train]
anneal_ent_coef = 0
anneal_lr = 1
beta1 = 0.912123272473036
beta2 = 0.9998531683245929
clip_coef = 0.1431940333434729
ent_coef = 0.0001052055453422444
eps = 1.8160899549063337e-11
gae_lambda = 0.9188274005690441
gamma = 0.9883613879184189
gpus = 1
horizon = 64
learning_rate = 0.006970704346010248
max_grad_norm = 1.3538062792589087
min_ent_coef_ratio = 0.1
min_lr_ratio = 0
minibatch_size = 8192
prio_alpha = 0
prio_beta0 = 0.4379690073325129
replay_ratio = 3.026959785601518
seed = 42
total_timesteps = 87_184_536
vf_clip_coef = 0.01
vf_coef = 4.265046324728165
vtrace_c_clip = 3.924473975798262
vtrace_rho_clip = 4.063738171458558

[sweep]
metric = perf

[sweep.train.total_timesteps]
distribution = log_normal
min = 3e7
max = 2e8
mean = 8e7
scale = auto

# hover
[sweep.env.hover_alpha_dist]
distribution = log_normal
min = 0.001
max = 10.0
mean = 1.0
scale = auto

[sweep.env.alpha_hover]
distribution = log_normal
min = 0.0001
max = 1.0
mean = 0.01
scale = auto

# race
[sweep.env.race_alpha_dist]
distribution = log_normal
min = 0.001
max = 10.0
mean = 1.0
scale = auto

[sweep.env.ring_reward]
distribution = log_normal
min = 0.1
max = 100.0
mean = 1.0
scale = auto

# fracs
[sweep.env.hover_frac]
distribution = uniform
min = 0.1
max = 1.0
scale = auto

[sweep.env.race_frac]
distribution = uniform
min = 0.1
max = 1.0
scale = auto