[base]
env_name = nethack
cudagraphs = 2
checkpoint_interval = 25


[vec]
total_agents = 1024
num_buffers = 6
num_threads = 32

[env]
score_coef = 0.024632759885043976
descent_coef = 0.025223421745275164
scout_coef = 0.006901238385104967
hp_coef = 0.0005
illegal_penalty = -0.07053028720066883
death_penalty = 0.0

[policy]
hidden_size = 128
num_layers = 5
expansion_factor = 1

[train]
total_timesteps = 259_104_076
learning_rate = 0.00032351934766163535
gamma = 0.9852336081810699
gae_lambda = 0.8197996981843496
clip_coef = 0.11740292639026277
vf_clip_coef = 0.01
vf_coef = 4.8855880436308095
vtrace_c_clip = 5.0
vtrace_rho_clip = 1.2572955344733667
ent_coef = 0.010061495965867038
beta1 = 0.9427441554541258
beta2 = 0.9975071300645509
eps = 1.5309118828224477e-09
max_grad_norm = 5.0
prio_alpha = 0.9227034456921525
prio_beta0 = 0.0
replay_ratio = 3.471164730880491
horizon = 256

[sweep]
metric = max_depth
#max_suggestion_cost = 1500

[sweep.train.total_timesteps]
distribution = log_normal
min = 2e7
mean = 5e8
max = 6e8
scale = auto

[sweep.env.score_coef]
distribution = log_normal
min = 0.001
mean = 0.01
max = 10.0
scale = auto

[sweep.env.descent_coef]
distribution = log_normal
min = 0.01
mean = 0.1
max = 1.0
scale = auto

[sweep.env.scout_coef]
distribution = log_normal
min = 0.0001
mean = 0.001
max = 0.1
scale = auto

[sweep.env.hp_coef]
distribution = log_normal
min = 0.0005
mean = 0.005
max = 0.1
scale = auto

[sweep.env.illegal_penalty]
distribution = uniform
min = -0.10
mean = -0.001
max = 0.0
scale = auto

[sweep.env.death_penalty]
distribution = uniform
min = -1.0
mean = -0.5
max = 0.0
scale = auto
