#define POWER_GRID_NO_RENDER

#include "power_grid_solver.c"
#include "power_grid_ac.c"
#include "power_grid.h"

#include <stdint.h>
#include <stdio.h>

static int outage_is_solvable(const PowerGridOperatingPoint *point, int outage_line)
{
    PowerGridTopology outage;
    PowerGridSolveResult solution;
    power_grid_topology_normal(&outage);
    outage.line_closed[outage_line] = 0;
    return power_grid_solve(&outage, point, &solution) == POWER_GRID_SOLVE_OK;
}

static uint32_t certified_outage_mask(const PowerGridOperatingPoint *point)
{
    uint32_t mask = 0;
    for (int line = 0; line < POWER_GRID_NUM_BRANCHES; line++)
    {
        if (outage_is_solvable(point, line))
            mask |= UINT32_C(1) << line;
    }
    return mask;
}

static void historical_point(PowerGridOperatingPoint *point,
                             const PowerGridOfflineScenario *scenario, int period)
{
    power_grid_operating_point_nominal(point);
    for (int load = 0; load < POWER_GRID_NUM_LOADS; load++)
        point->load_mw[load] *= scenario->load_scale[period];
    point->generator_mw[2] = scenario->solar_mw[period];
    point->generator_mw[3] = scenario->wind_mw[period];
}

int main(int argc, char **argv)
{
    if (argc != 2)
    {
        fprintf(stderr, "usage: %s OUTPUT_HEADER\n", argv[0]);
        return 2;
    }
    FILE *output = fopen(argv[1], "w");
    if (output == NULL)
    {
        perror(argv[1]);
        return 1;
    }

    uint32_t mask = (UINT32_C(1) << POWER_GRID_NUM_BRANCHES) - 1;
    for (int scenario_index = 0;
         scenario_index < POWER_GRID_OFFLINE_SCENARIO_COUNT; scenario_index++)
    {
        const PowerGridOfflineScenario *scenario =
            &POWER_GRID_OFFLINE_SCENARIOS[scenario_index];
        for (int period = 0; period < POWER_GRID_NUM_PERIODS; period++)
        {
            PowerGridOperatingPoint point;
            historical_point(&point, scenario, period);
            mask &= certified_outage_mask(&point);
        }
    }

    for (int profile = 0; profile < POWER_GRID_NUM_PROFILES; profile++)
    {
        PowerGridOperatingPoint point;
        power_grid_operating_point_profile(&point, (PowerGridProfile)profile);
        mask &= certified_outage_mask(&point);
    }
    fprintf(output,
            "/* Generated by build_contingency_catalog.c; do not edit manually. */\n"
            "#ifndef POWER_GRID_CONTINGENCIES_DATA_H\n"
            "#define POWER_GRID_CONTINGENCIES_DATA_H\n\n"
            "#include <stdint.h>\n\n"
            "#define POWER_GRID_SOLVABLE_CONTINGENCY_MASK UINT32_C(0x%05x)\n\n"
            "#endif\n",
            mask);
    if (fclose(output) != 0)
    {
        perror(argv[1]);
        return 1;
    }
    fprintf(stderr, "certified %d line outages across every operating point\n",
            __builtin_popcount(mask));
    return 0;
}
