/* Generated by build_random_event_catalog.c; do not edit manually. */
#ifndef POWER_GRID_RANDOM_EVENTS_DATA_H
#define POWER_GRID_RANDOM_EVENTS_DATA_H

#include <stdint.h>

#define POWER_GRID_SOLVABLE_RANDOM_EVENT_MASK UINT32_C(0xfdfff)

#endif
