/* Generated by build_contingency_catalog.c; do not edit manually. */
#ifndef POWER_GRID_CONTINGENCIES_DATA_H
#define POWER_GRID_CONTINGENCIES_DATA_H

#include <stdint.h>

#define POWER_GRID_SOLVABLE_CONTINGENCY_MASK UINT32_C(0xfdfff)

#endif
